In [24]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Download from the 🤗 Hub
model = SentenceTransformer("Lauther/d4-embeddings-v2.0")

In [26]:
sentences = [
    'flow rate',
    'What is a flow computer?\nA flow computer is a device used in measurement engineering. It collects analog and digital data from flow meters and other sensors.\n\nKey features of a flow computer:\n- It has a unique name, firmware version, and manufacturer information.\n- It is designed to record and process data such as temperature, pressure, and fluid volume (for gases or oils).',
    'What is a Fluid?\nA Fluid is the substance measured within a measurement system. It can be a gas or liquid, such as hydrocarbons, water, or other industrial fluids. Proper classification of fluids is essential for ensuring measurement accuracy, regulatory compliance, and operational efficiency. By identifying fluids correctly, the system applies the appropriate measurement techniques, processing methods, and reporting standards.',
    '''What is a Measured Magnitude Value?
A Measured Magnitude Value represents a **DAILY** recorded physical measurement of a variable within a monitored fluid. These values are essential for tracking system performance, analyzing trends, and ensuring accurate monitoring of fluid properties.

Key Aspects of a Measured Magnitude Value:
- Measurement Date: The timestamp indicating when the measurement was recorded.
- Measured Value: The daily numeric result of the recorded physical magnitude.
- Measurement System Association: Links the measured value to a specific measurement system responsible for capturing the data.
- Variable Association: Identifies the specific variable (e.g., temperature, pressure, flow rate) corresponding to the recorded value.
Measured magnitude values are crucial for real-time monitoring, historical analysis, and calibration processes within measurement systems.

Database advices:
This values also are in **historics of a flow computer report**. Although, to go directly instead querying the flow computer report you can do it by going to the table of variables data in the database.'''
]
embeddings = model.encode(sentences, convert_to_numpy=True)

similarities = cosine_similarity(embeddings)

print(similarities.shape)  # (3, 3)
print(similarities)

(4, 4)
[[1.         0.44689536 0.5141099  0.96432227]
 [0.44689536 0.99999994 0.7507417  0.30573517]
 [0.5141099  0.7507417  0.99999976 0.30236965]
 [0.96432227 0.30573517 0.30236965 1.        ]]
